# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
#  - osx
julia:
  - 1.4
  - nightly
arch:
  - x64
  - x86
notifications:
  email: false
jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
