name = "SimpleTranslations"
uuid = "d3f95609-6610-4916-a459-7889d74a9b0e"
authors = ["Daniel Molina"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
